### ISSUE TITLE
Not a wrapper

### ISSUE THREAD

**Issue by MarzaElise** [TheFarGG/pycatapi#4]
This repository cannot be called as an API wrapper for [thecatapi](https://thecatapi.com) for the following reasons

- This does not wrap the entire API
  - You can only get specific data from the API using this (url, description as of now)
  - Only `images/search` endpoint is supported
  - Very poor code quality
  - Cannot be used in a production environment

This could rather be used as a module for getting random cat images but not an API wrapper.

So renaming the module and removing "An API wrapper for TheCatApi" from description and README would be better

**Comment by TheGenocides** [comment]
ok boomer

**Comment by SohamGhugare** [comment]
Geno bald

**Comment by BruceCodesGithub** [comment]
> Very poor code quality

This seemed good to me 👀

**Comment by MarzaElise** [comment]
> ok boomer

im 14 so im gen-z
